### ISSUE TITLE
SPIKE: Investigate Next.js Server-Side Rendering

### ISSUE THREAD

**Issue by JNygaard-Skylight** [CDCgov/dibbs-ecr-viewer#148]
## What needs to be done

The Next.js framework allows for lot of control over exactly where rendering and logic can occur. Currently we force everything to run client-side, like a traditional website. However, because the eCR Viewer has minimal user interactivity we can potentially leverage Next.js's more advance features, such as server components, and caching to improve the user experience.

## Why it needs to be done

We can potentially improve the speed at which the `view-data` page loads an eCR and make loading a more seamless experience

## Timebox

Depending how familiar and confident one is with Next.js, 3-5 days?

## To-do list

- [ ] Try moving the eCR Viewer to server-side rendering
- [ ] Evaluate how large of a lift it would be 
- [ ] Discuss with leads if lift would be worth the performance tradeoffs

## Additional context

This came out of a loading page improvement ticket - CDCgov/phdi#2219.

**Comment by mcmcgrath13** [comment]
@JNygaard-Skylight do you think we've pretty much done this at this point? or is there more to do here?

**Comment by JNygaard-Skylight** [comment]
This ticket can definitely be closed. Any new SSR-related work, if any, can go in a new ticket.
