### ISSUE TITLE
SPIKE: Testing authorization (roles) with Next Auth

### ISSUE THREAD

**Issue by austin-hall-skylight** [CDCgov/dibbs-ecr-viewer#58]
## What needs to be done

Test out using roles in Next Auth to control access to the eCR Library.

## Why it needs to be done

We will need to define roles to control who can see the library and also who can see what eCR's. This is the initial proof of concept for that work.

## Timebox

_How much time should be dedicated to this spike?_

## To-do list

Choose one:
- [ ] [Create a role in Keycloak and assign it to a user or group](https://www.keycloak.org/docs/latest/server_admin/#assigning-permissions-using-roles-and-groups)
- [x] [Create a role in Azure AD and assign it to a user or group](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/custom-create)

Then
- [ ] [Use a role created in Keycloak or Azure AD to control access to the eCR Library](https://authjs.dev/guides/role-based-access-control)
